routes/web.php
<?php
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
/*Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');*/

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/', 'HomeController@index');

/**
 * Rutas para módulo Datos
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'user_access:access_data', 'user_connection']], function(){
    /**
     * Rutas de comunidades
     */
    Route::resource('community', 'CommunitiesController');

    /**
     * Rutas de propiedades
     */
    Route::resource('property', 'PropertiesController', ['except' => ['show']]);

    /**
     * Ruta person
     */
    Route::resource('person', 'PersonsController');

    /**
     * Rutas de Proveedores
     */
    Route::resource('supplier', 'SuppliersController');

    /**
     * Ruta para la gestión de coeficientes
     */
    Route::resource('coefficient', 'CoefficientController', [
        'except' => ['create', 'store', 'show', 'destroy']
    ]);

    /**
     * Ruta de Contratos
     */
    Route::resource('contract', 'ContractsController');

    /**
     * Ruta de códigos postales
     */
    Route::resource('postal-code', 'PostalCodesController');
    Route::get('postal-code/get-data/{id}', 'PostalCodesController@getData');
});

/**
 * Rutas para módulo Gestión
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'user_access:access_management', 'user_connection']], function(){
    /**
     * Ruta de documents
     */
    Route::post('pages/undo/{id}', [
        'uses' => 'PagesController@postUndelete',
        'as' => 'pages.undelete'
    ]);
    Route::resource('pages', 'PagesController', ['except' => ['show']]);

    Route::post('tags/undo/{id}', [
        'uses' => 'TagsController@postUndelete',
        'as' => 'tags.undelete'
    ]);
    Route::resource('tags', 'TagsController', ['except' => ['show']]);

    Route::post('documents/undo/{id}', [
        'uses' => 'DocumentsController@postUndelete',
        'as' => 'documents.undelete'
    ]);
    Route::resource('documents', 'DocumentsController');

    /**
     * Ruta de templates
     */
    Route::post('models/undo/{id}', [
        'uses' => 'ModelsController@postUndelete',
        'as' => 'models.undelete'
    ]);
    Route::resource('models', 'ModelsController', ['except' => ['show']]);

    Route::post('templates/undo/{id}', [
        'uses' => 'TemplatesController@postUndelete',
        'as' => 'templates.undelete'
    ]);
    Route::resource('templates', 'TemplatesController', ['except' => ['show']]);

    /**
     * Ruta de incidences
     */
    Route::post('communicator-types/undo/{id}', [
        'uses' => 'CommunicatorTypesController@postUndelete',
        'as' => 'communicator-types.undelete'
    ]);
    Route::resource('communicator-types', 'CommunicatorTypesController', ['except' => ['show']]);

    Route::post('receptions/undo/{id}', [
        'uses' => 'ReceptionsController@postUndelete',
        'as' => 'receptions.undelete'
    ]);
    Route::resource('receptions', 'ReceptionsController', ['except' => ['show']]);

    Route::post('reasons/undo/{id}', [
        'uses' => 'ReasonsController@postUndelete',
        'as' => 'reasons.undelete'
    ]);
    Route::resource('reasons', 'ReasonsController', ['except' => ['show']]);

    Route::post('sectors/undo/{id}', [
        'uses' => 'SectorsController@postUndelete',
        'as' => 'sectors.undelete'
    ]);
    Route::resource('sectors', 'SectorsController', ['except' => ['show']]);

    Route::get('incidences/communities', [
        'uses' => 'IncidencesController@getCommunities',
        'as' => 'incidences.communities'
    ]);

    Route::post('incidences/undo/{id}', [
        'uses' => 'IncidencesController@postUndelete',
        'as' => 'incidences.undelete'
    ]);
    Route::resource('incidences', 'IncidencesController');

    /**
     * Ruta de presupuestos
     */
    Route::post('invoicing-concepts/undo/{id}', [
        'uses' => 'InvoicingConceptsController@postUndelete',
        'as' => 'invoicing-concepts.undelete'
    ]);
    Route::resource('invoicing-concepts', 'InvoicingConceptsController', ['except' => ['show']]);

    Route::get('budgets/community-properties', [
        'uses' => 'BudgetsController@getCommunityProperties',
        'as' => 'budgets.properties'
    ]);
    Route::get('budgets/data', [
        'uses' => 'BudgetsController@getBudgetData',
        'as' => 'budgets.data'
    ]);
    Route::post('budgets/undo/{id}', [
        'uses' => 'BudgetsController@postUndelete',
        'as' => 'budgets.undelete'
    ]);
    Route::resource('budgets', 'BudgetsController', ['except' => ['show']]);

    /**
     * Ruta de readings
     */
    Route::post('rates/undo/{id}', [
        'uses' => 'RatesController@postUndelete',
        'as' => 'rates.undelete'
    ]);
    Route::resource('rates', 'RatesController', ['except' => ['show']]);

    Route::get('readings/data', [
        'uses' => 'ReadingsController@getReadingData',
        'as' => 'readings.data'
    ]);
    Route::get('readings/community-properties', [
        'uses' => 'ReadingsController@getCommunityProperties',
        'as' => 'readings.properties'
    ]);
    Route::post('readings/undo/{id}', [
        'uses' => 'ReadingsController@postUndelete',
        'as' => 'readings.undelete'
    ]);
    Route::resource('readings', 'ReadingsController', ['except' => ['show']]);

    /**
     * Ruta de Cuotas de recibos
     */
    Route::get('receiptdues/getProperties', 'ReceiptDuesController@getProperties');
    Route::get('receiptdues/getReceipDueLastMonth', 'ReceiptDuesController@getReceipDueLastMonth');
    Route::post('receiptdues/postUndelete/{id}', [
        'uses' => 'ReceiptDuesController@postUndelete',
        'as' => 'receiptdues.undelete'
    ]);
    Route::resource('receiptdues', 'ReceiptDuesController');

    /**
     * Ruta para emision de recibos
     */
    Route::post('issue-receipts/undo/{id}', [
        'uses' => 'IssueReceiptsController@postUndelete',
        'as' => 'issue-receipts.undelete'
    ]);
    Route::resource('issue-receipts', 'IssueReceiptsController', ['except' => ['edit']]);

    /**
     * Ruta para recibos a bancos
     */
    Route::post('receipts-banks/undo/{id}', [
        'uses' => 'ReceiptsToBanksController@postUndelete',
        'as' => 'receipts-banks.undelete'
    ]);
    Route::resource('receipts-banks', 'ReceiptsToBanksController', ['except' => ['edit']]);

    /**
     * Ruta para cobros
     */
    Route::get('charges/receipts-and-properties', [
        'uses' => 'ChargesController@getReceiptsAndProperties',
        'as' => 'charges.receipts_and_properties'
    ]);
    Route::post('charges/undo/{id}', [
        'uses' => 'ChargesController@postUndelete',
        'as' => 'charges.undelete'
    ]);
    Route::resource('charges', 'ChargesController', ['except' => ['show']]);
});

/**
 * Rutas para módulo Correo
 */
Route::group(['namespace' => 'Common', 'middleware' => ['auth', 'user_access:access_mail', 'user_connection']], function(){

    Route::resource('message', 'MessagesController', ['except' => ['show', 'index', 'update', 'edit', 'destroy']]);
    Route::get('received-messages', [
        'uses' => 'MessagesController@received',
        'as'   => 'received.messages'
    ]);
    Route::get('sent-messages', [
        'uses' => 'MessagesController@sent',
        'as'   => 'sent.messages'
    ]);
    Route::get('show-sent-messages/{id}', [
        'uses' => 'MessagesController@showSent',
        'as'   => 'show.sent.messages'
    ]);
    Route::get('show-received-messages/{id}', [
        'uses' => 'MessagesController@showReceived',
        'as'   => 'show.received.messages'
    ]);
    Route::get('delete-received-message/{id}', [
        'uses' => 'MessagesController@destroyReceived',
        'as'   => 'delete.received.message'
    ]);
    Route::get('delete-sent-message/{id}', [
        'uses' => 'MessagesController@destroySent',
        'as'   => 'delete.sent.message'
    ]);
    Route::get('download-message-file/{fileName}', [
        'uses' => 'MessagesController@download',
        'as'   => 'download.message.file'
    ]);

    /**
     * Text message
     */
    Route::get('text-messages/create', [
        'uses' => 'TextMessageController@create',
        'as'   => 'text.messages.create'
    ]);

    Route::post('text-messages/store', [
        'uses' => 'TextMessageController@store',
        'as'   => 'text.messages.store'
    ]);

    Route::get('sent-text-messages', [
        'uses' => 'TextMessageController@sent',
        'as'   => 'sent.text.messages'
    ]);
});

/**
 * Rutas para módulo Informes
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'user_access:access_reports', 'user_connection']], function(){
    Route::group(['prefix' => 'report'], function () {
        // Dossier
        Route::get('/dossier', ['as' => 'report.dossier', 'uses' => 'ReportController@dossier']);
        Route::get('/view-report-dossier', ['as' => 'report.viewdossier', 'uses' => 'ReportController@dossierViewReport']);
        Route::get('/export-dossier-pdf', ['as' => 'report.dossier-pdf', 'uses' => 'ReportController@dossierExportPdf']);
        Route::get('/export-dossier-excel', ['as' => 'report.dossier-excel', 'uses' => 'ReportController@dossierExportExcel']);

        // Liquidation Cons.

app/Models/Charge.php
<?php

namespace Edifalia\Models;

use Edifalia\Models\Common\Property;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \Venturecraft\Revisionable\RevisionableTrait;
use Illuminate\Support\Facades\Auth;

class Charge extends Model
{
    use SoftDeletes;
    use RevisionableTrait;

    protected $revisionCreationsEnabled = false;

    protected $fillable = ['community_id', 'property_id', 'issue_receipt_id', 'pending', 'charge_type'];

    protected $dates = ['deleted_at'];

    /**
     * Get the user that owns the Charge.
     */
    public function user()
    {
        return $this->belongsTo('Edifalia\User');
    }

    /**
     * Get the community that owns the Charge.
     */
    public function community()
    {
        return $this->belongsTo('Edifalia\Models\Backend\Community');
    }

    /**
     * Get the property that owns the Charge.
     */
    public function property()
    {
        return $this->belongsTo('Edifalia\Models\Common\Property');
    }

    /**
     * Get the issueReceipt that owns the Charge.
     */
    public function issueReceipt()
    {
        return $this->belongsTo('Edifalia\Models\IssueReceipt');
    }

    /**
     * full name Accessor
     */
    public function getOwnerFullNameAttribute()
    {
        return $this->property->person->first_name.' '.$this->property->person->last_name;
    }

    /**
     * State Accessor
     */
    public function getStateAttribute()
    {
        return ($this->attributes['pending'] <= 0) ? "check" : "close";
    }

    /**
     * State class Accessor
     */
    public function getStateClassAttribute()
    {
        return ($this->attributes['pending'] <= 0) ? "success" : "danger";
    }

    /**
     * amount Accessor
     */
    public function getAmountAttribute()
    {
        $property = Property::find($this->attributes['property_id']);
        $receiptDues = $property->receiptDues()->where('issue_receipt_id', $this->attributes['issue_receipt_id'])->get();
        $sum = 0;
        foreach ($receiptDues as $receiptDue) {
            $sum += $receiptDue->pivot->amount;
        }
        return $sum;
    }

    //// Filters
    public static function filterCharges($searchFields, $paginate = true, $pagesNumber = 10)
    {
        if (empty($searchFields)) {
            if (Auth::user()->can('admin'))
                return ($paginate) ? Charge::paginate($pagesNumber) : Charge::all();
            else
                return ($paginate) ? Auth::user()->charges()->paginate($pagesNumber) : Auth::user()->charges()->get();
        }

        if (Auth::user()->can('admin')){
            $q = Charge::state($searchFields)->community($searchFields['community'])
                ->date($searchFields);
        } else {
            $q = Charge::where('user_id', Auth::user()->id)
                ->state($searchFields)
                ->community($searchFields['community'])
                ->date($searchFields);
        }

        return ($paginate) ? $q->paginate($pagesNumber) : $q->get();
    }

    public function scopeState($query, $searchFields)
    {
        $state_value = (!empty($searchFields['state'])) ? $searchFields['state'] : "";
        if ($state_value == 1){
            $query->where('pending', '<=', '0');
        } else if($state_value == 2) {
            $query->where('pending', '>', '0');
        }
    }

    public function scopeCommunity($query, $community_id)
    {
        if (!empty($community_id) && is_numeric(trim($community_id))){
            $query->where('community_id', $community_id);
        }
    }

    public function scopeDate($query, $searchFields)
    {
        if (!empty($searchFields['date_from']) || !empty($searchFields['date_until'])){
            $date_from =  (!empty($searchFields['date_from'])) ? $searchFields['date_from'] : "";
            $date_until =  (!empty($searchFields['date_until'])) ? $searchFields['date_until'] : "";
            $chargeIds = $this->getChargeIds($date_from, $date_until);
            $query->whereIn('id', $chargeIds);
        }
    }

    private function getChargeIds($date_from, $date_until)
    {
        $chargeIds = [];
        if (!empty($date_from) || !empty($date_until)){
            $charges = (Auth::user()->can('admin')) ? Charge::all() : Auth::user()->charges()->get();
            foreach ($charges as $charge){
                if (!empty($date_from) && !empty($date_until)){
                    if ($charge->issueReceipt->date >= $date_from && $charge->issueReceipt->date <= $date_until)
                        $chargeIds[] = $charge->id;
                } elseif (!empty($date_from) && empty($date_until)) {
                    if ($charge->issueReceipt->date >= $date_from)
                        $chargeIds[] = $charge->id;
                } elseif (empty($date_from) && !empty($date_until)) {
                    if ($charge->issueReceipt->date <= $date_until)
                        $chargeIds[] = $charge->id;
                }
            }
        }
        return $chargeIds;
    }
}

resources/views/backend/management/charges/create_or_edit.blade.php
@extends('layouts.dashboard')

@section('breadcrumb_title')
    @lang('dashboard.mnu_charges')
@endsection

@section('breadcrumb_subtitle')
    {{$title}}
@endsection

@section('breadcrumb_map')
    <li>
        <a href="{{ url('dashboard') }}">
            <i class="fa fa-dashboard"></i> @lang('dashboard.home')
        </a>
    </li>
    <li><a href="#">@lang('dashboard.mnu_management')</a></li>
    <li class="active">@lang('dashboard.mnu_charges')</li>
@endsection

@section('modals')
    @include('backend.partials.modals')
@endsection

@section('content')
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">@lang('dashboard.mnu_charges')</h3>
            <div class="btn-group btn-group-sm pull-right">
                <a data-toggle="tooltip" class="btn btn-primary"
                   title="@lang('dashboard.buttons.back')"
                   href="{{route('charges.index')}}">
                    <i class="fa fa-reply"></i></a>
                @if(isset($charge))
                    <a data-toggle="tooltip" class="btn btn-primary"
                       title="@lang('dashboard.buttons.new')"
                       href="{{route('charges.create')}}">
                        <i class="fa fa-plus"></i></a>
                @endif
            </div>
        </div>
        @if(!isset($charge))
            {!! Form::open($header) !!}
        @else
            {!! Form::model($charge, $header) !!}
        @endif
        <div class="box-body">
            @include('backend.partials.messages')
            @include('backend.management.charges.fields')
        </div>
        <div class="box-footer">
            <button type="submit" class="btn btn-info">
                <i class="fa fa-save"></i>
                @if(!isset($charge)) @lang('dashboard.buttons.save') @else
                    @lang('dashboard.buttons.update')
                @endif
            </button>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function(){
            selectCommunity();
            $('#community').on('change', selectCommunity);

            function selectCommunity() {
                $("#pleaseWait").modal("show");
                var community_id = $('#community').val();
                var route = $('#community').data('route');
                var charge = $('#community').data('id');
                if ($.trim(community_id) != '') {
                    $.get(route, {community_id:community_id, charge_id:charge}, function(data) {
                        if (data.data) {
                            $('#issue_receipt').empty();
                            $('#issue_receipt').append("<option value=''>" + data.select_receipts + "</option>");
                            $.each(data.receipts, function(index, value){
                                $('#issue_receipt').append("<option value='" + index + "'>" + value + "</option>");
                            });
                            $("#issue_receipt option[value='" + data.issueReceiptValue + "']").attr("selected", true);

                            $('#property').empty();
                            $('#property').append("<option value=''>" + data.select_properties + "</option>");
                            $.each(data.properties, function(index, value){
                                $('#property').append("<option value='" + index + "'>" + value + "</option>");
                            });
                            $("#property option[value='" + data.propertyValue + "']").attr("selected", true);
                        } else {
                            toastr.error(data.message);
                        }
                        $("#pleaseWait").modal("hide");
                    });
                } else {
                    $("#pleaseWait").modal("hide");
                }
            }
        });
    </script>
@endsection

resources/views/backend/management/charges/fields.blade.php
@inject('communities', 'Edifalia\Services\Communities')

<div class="row">
    <div class="form-group col-md-6 {{ $errors->has('community_id') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.community')) !!}
        @can('admin')
            {!! Form::select('community_id', $communities->all(), null, [
                'class' => 'form-control',
                'id' => 'community',
                'data-route' => route('charges.receipts_and_properties'),
                'data-id' => (isset($charge))?$charge->id:''])
            !!}
        @elsecan('employee')
            {!! Form::select('community_id', $communities->ofEmployee(), null, [
                'class' => 'form-control',
                'id' => 'community',
                'data-route' => route('charges.receipts_and_properties'),
                'data-id' => (isset($charge))?$charge->id:''])
            !!}
        @endcan
    </div>
    <div class="form-group col-md-6 {{ $errors->has('issue_receipt_id') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.issue_receipt')) !!}
        {!! Form::select('issue_receipt_id', [], null,
            ['class' => 'form-control',
             'id' => 'issue_receipt',])
        !!}
    </div>
</div>

<div class="row">
    <div class="form-group col-md-6 {{ $errors->has('property_id') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.property')) !!}
        {!! Form::select('property_id', [], null,
            ['class' => 'form-control',
             'id' => 'property'])
        !!}
    </div>
    <div class="form-group col-md-6 {{ $errors->has('pending') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.pending')) !!}
        {!! Form::text('pending', null, [
            'class' => 'form-control',
            'placeholder' => trans('dashboard.fields.pending'),
            'required' => true])
        !!}
    </div>
</div>

<div class="row">
    <div class="form-group col-md-4 {{ $errors->has('charge_type') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.charge_type')) !!}
        {!! Form::select('charge_type', [
                '' => trans('dashboard.fields.select_charge_type'),
                '1' => trans('dashboard.charge_type.1'),
                '2' => trans('dashboard.charge_type.2'),
            ], null,['class' => 'form-control'])
        !!}
    </div>
</div>

resources/views/backend/management/charges/index.blade.php
@extends('layouts.dashboard')

@section('breadcrumb_title')
    @lang('dashboard.mnu_charges')
@endsection

@section('breadcrumb_subtitle')
    @lang('dashboard.titles.charges_list')
@endsection

@section('breadcrumb_map')
    <li>
        <a href="{{ url('dashboard') }}">
            <i class="fa fa-dashboard"></i> @lang('dashboard.home')
        </a>
    </li>
    <li><a href="#">@lang('dashboard.mnu_management')</a></li>
    <li class="active">@lang('dashboard.mnu_charges')</li>
@endsection

@section('modals')
    @include('backend.partials.modals')
@endsection

@section('content')
    @include('backend.management.charges.search')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">@lang('dashboard.mnu_charges')</h3>
        </div>
        <div class="box-body table-responsive">
            <table class="table table-hover">
                @if($charges->count())
                    <tr>
                        <th>@lang('dashboard.tables.floor')</th>
                        <th>@lang('dashboard.tables.date')</th>
                        <th>@lang('dashboard.tables.receipt')</th>
                        <th>@lang('dashboard.tables.property')</th>
                        <th>@lang('dashboard.tables.owner')</th>
                        <th>@lang('dashboard.tables.amount')</th>
                        <th>@lang('dashboard.tables.state')</th>
                        <th>@lang('dashboard.tables.pending')</th>
                        <th>@lang('dashboard.tables.charge_type')</th>
                        <th>@lang('dashboard.tables.actions')</th>
                    </tr>
                @endif
                @forelse($charges as $charge)
                    <tr data-id="{{$charge->id}}"
                        data-rundo="{{route('charges.undelete', $charge->id)}}">
                        <td>{{$charge->property->building_number}}</td>
                        <td>{{$charge->issueReceipt->date}}</td>
                        <td>{{$charge->issueReceipt->id}}</td>
                        <td>{{$charge->property->property_number}}</td>
                        <td>{{$charge->owner_full_name}}</td>
                        <td>{{$charge->amount}}</td>
                        <td>
                            <div class="text-{{$charge->state_class}}">
                                <i class='fa fa-{{$charge->state}}'></i>
                            </div>
                        </td>
                        <td>{{$charge->pending}}</td>
                        <td>@lang('dashboard.charge_type.'.$charge->charge_type)</td>
                        <td>
                            <div class="btn-group btn-group-xs">
                                <a data-toggle="tooltip" class="btn btn-info"
                                   title="@lang('dashboard.buttons.edit')"
                                   href="{{route('charges.edit', $charge->id)}}">
                                    <i class="fa fa-pencil-square-o"></i></a>

                                <a data-toggle="tooltip" class="btn btn-info delete_record"
                                   title="@lang('dashboard.buttons.delete')"
                                   href="{{route('charges.destroy', $charge->id)}}">
                                    <i class="fa fa-trash-o"></i></a>
                            </div>
                        </td>
                    </tr>
                @empty
                    <div class="alert alert-warning">
                        <h4><i class="icon fa fa-warning"></i> @lang('dashboard.messages.notice')</h4>
                        @lang('dashboard.messages.no_stored_records')
                    </div>
                @endforelse
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            {{$charges->links()}}
            <a data-toggle="tooltip" class="btn btn-primary pull-right"
               title="@lang('dashboard.buttons.new')"
               href="{{route('charges.create')}}">
                <i class="fa fa-plus"></i> @lang('dashboard.buttons.new')</a>
        </div>
        <!-- /.box-footer-->
    </div>
@endsection

@section('scripts')
    {{-- Backend scripts  --}}
    {!! Html::script('js/code01.js') !!}
    {{-- bootstrap datepicker --}}
    {!! Html::script('static/plugins/datepicker/bootstrap-datepicker.js') !!}
    <script>
        $(document).ready(function(){
            $("#datepicker").datepicker();
        });
        $(document).ready(function(){
            $("#datepicker2").datepicker();
        });
    </script>
@endsection

resources/views/backend/management/charges/search.blade.php
@inject('communities', 'Edifalia\Services\Communities')

{!! Form::model(Request::all(),
    [	'route' => 'charges.index',
        'method' => 'GET',
        'rol' => 'search',
        'class' => 'form-inline'
    ])
!!}
    <div class="radio">
        <label>
            <div class="text-success">
                {!! Form::radio('state', 1, null) !!}
                <i class='fa fa-check'></i>
            </div>
        </label>
    </div>
    <div class="checkbox">
        <label>
            <div class="text-danger">
                {!! Form::radio('state', 2, null) !!}
                <i class='fa fa-close'></i>
            </div>
        </label>
    </div>
    @can('admin')
        <div class="form-group">
            {!! Form::select('community', $communities->all(), null, [
                'class' => 'form-control'])
            !!}
        </div>
    @elsecan('employee')
        <div class="form-group">
            {!! Form::select('community', $communities->ofEmployee(), null, [
                'class' => 'form-control'])
            !!}
        </div>
    @endcan
    <div class="form-group">
        {!! Form::text('date_from', null, [
            'class' => 'form-control',
            'placeholder' => trans('dashboard.fields.from'),
            'id' => 'datepicker'])
        !!}
    </div>
    <div class="form-group">
        {!! Form::text('date_until', null, [
            'class' => 'form-control',
            'placeholder' => trans('dashboard.fields.until'),
            'id' => 'datepicker2'])
        !!}
    </div>

    <button type="submit" class="btn btn-default" data-toggle="tooltip" title="@lang('dashboard.buttons.search')">
        <i class="fa fa-search"></i>
    </button>
    <a data-toggle="tooltip" class="btn btn-default"
       title="@lang('dashboard.buttons.refresh')"
       href="{{route('charges.index')}}">
        <i class="fa fa-refresh"></i></a>
{!! Form::close() !!}