routes/web.php
<?php
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
/*Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');*/

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/', 'HomeController@index');

/**
 * Rutas para módulo Datos
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'user_access:access_data', 'user_connection']], function(){
    /**
     * Rutas de comunidades
     */
    Route::resource('community', 'CommunitiesController');

    /**
     * Rutas de propiedades
     */
    Route::resource('property', 'PropertiesController', ['except' => ['show']]);

    /**
     * Ruta person
     */
    Route::resource('person', 'PersonsController');

    /**
     * Rutas de Proveedores
     */
    Route::resource('supplier', 'SuppliersController');

    /**
     * Ruta para la gestión de coeficientes
     */
    Route::resource('coefficient', 'CoefficientController', [
        'except' => ['create', 'store', 'show', 'destroy']
    ]);

    /**
     * Ruta de Contratos
     */
    Route::resource('contract', 'ContractsController');

    /**
     * Ruta de códigos postales
     */
    Route::resource('postal-code', 'PostalCodesController');
    Route::get('postal-code/get-data/{id}', 'PostalCodesController@getData');
});

/**
 * Rutas para módulo Gestión
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'user_access:access_management', 'user_connection']], function(){
    /**
     * Ruta de documents
     */
    Route::post('pages/undo/{id}', [
        'uses' => 'PagesController@postUndelete',
        'as' => 'pages.undelete'
    ]);
    Route::resource('pages', 'PagesController', ['except' => ['show']]);

    Route::post('tags/undo/{id}', [
        'uses' => 'TagsController@postUndelete',
        'as' => 'tags.undelete'
    ]);
    Route::resource('tags', 'TagsController', ['except' => ['show']]);

    Route::post('documents/undo/{id}', [
        'uses' => 'DocumentsController@postUndelete',
        'as' => 'documents.undelete'
    ]);
    Route::resource('documents', 'DocumentsController');

    /**
     * Ruta de templates
     */
    Route::post('models/undo/{id}', [
        'uses' => 'ModelsController@postUndelete',
        'as' => 'models.undelete'
    ]);
    Route::resource('models', 'ModelsController', ['except' => ['show']]);

    Route::post('templates/undo/{id}', [
        'uses' => 'TemplatesController@postUndelete',
        'as' => 'templates.undelete'
    ]);
    Route::resource('templates', 'TemplatesController', ['except' => ['show']]);

    /**
     * Ruta de incidences
     */
    Route::post('communicator-types/undo/{id}', [
        'uses' => 'CommunicatorTypesController@postUndelete',
        'as' => 'communicator-types.undelete'
    ]);
    Route::resource('communicator-types', 'CommunicatorTypesController', ['except' => ['show']]);

    Route::post('receptions/undo/{id}', [
        'uses' => 'ReceptionsController@postUndelete',
        'as' => 'receptions.undelete'
    ]);
    Route::resource('receptions', 'ReceptionsController', ['except' => ['show']]);

    Route::post('reasons/undo/{id}', [
        'uses' => 'ReasonsController@postUndelete',
        'as' => 'reasons.undelete'
    ]);
    Route::resource('reasons', 'ReasonsController', ['except' => ['show']]);

    Route::post('sectors/undo/{id}', [
        'uses' => 'SectorsController@postUndelete',
        'as' => 'sectors.undelete'
    ]);
    Route::resource('sectors', 'SectorsController', ['except' => ['show']]);

    Route::get('incidences/communities', [
        'uses' => 'IncidencesController@getCommunities',
        'as' => 'incidences.communities'
    ]);

    Route::post('incidences/undo/{id}', [
        'uses' => 'IncidencesController@postUndelete',
        'as' => 'incidences.undelete'
    ]);
    Route::resource('incidences', 'IncidencesController');

    /**
     * Ruta de presupuestos
     */
    Route::post('invoicing-concepts/undo/{id}', [
        'uses' => 'InvoicingConceptsController@postUndelete',
        'as' => 'invoicing-concepts.undelete'
    ]);
    Route::resource('invoicing-concepts', 'InvoicingConceptsController', ['except' => ['show']]);

    Route::get('budgets/community-properties', [
        'uses' => 'BudgetsController@getCommunityProperties',
        'as' => 'budgets.properties'
    ]);
    Route::get('budgets/data', [
        'uses' => 'BudgetsController@getBudgetData',
        'as' => 'budgets.data'
    ]);
    Route::post('budgets/undo/{id}', [
        'uses' => 'BudgetsController@postUndelete',
        'as' => 'budgets.undelete'
    ]);
    Route::resource('budgets', 'BudgetsController', ['except' => ['show']]);

    /**
     * Ruta de readings
     */
    Route::post('rates/undo/{id}', [
        'uses' => 'RatesController@postUndelete',
        'as' => 'rates.undelete'
    ]);
    Route::resource('rates', 'RatesController', ['except' => ['show']]);

    Route::get('readings/data', [
        'uses' => 'ReadingsController@getReadingData',
        'as' => 'readings.data'
    ]);
    Route::get('readings/community-properties', [
        'uses' => 'ReadingsController@getCommunityProperties',
        'as' => 'readings.properties'
    ]);
    Route::post('readings/undo/{id}', [
        'uses' => 'ReadingsController@postUndelete',
        'as' => 'readings.undelete'
    ]);
    Route::resource('readings', 'ReadingsController', ['except' => ['show']]);

    /**
     * Ruta de Cuotas de recibos
     */
    Route::get('receiptdues/getProperties', 'ReceiptDuesController@getProperties');
    Route::get('receiptdues/getReceipDueLastMonth', 'ReceiptDuesController@getReceipDueLastMonth');
    Route::post('receiptdues/postUndelete/{id}', [
        'uses' => 'ReceiptDuesController@postUndelete',
        'as' => 'receiptdues.undelete'
    ]);
    Route::resource('receiptdues', 'ReceiptDuesController');

    /**
     * Ruta para emision de recibos
     */
    Route::post('issue-receipts/undo/{id}', [
        'uses' => 'IssueReceiptsController@postUndelete',
        'as' => 'issue-receipts.undelete'
    ]);
    Route::resource('issue-receipts', 'IssueReceiptsController', ['except' => ['edit']]);

    /**
     * Ruta para recibos a bancos
     */
    Route::post('receipts-banks/undo/{id}', [
        'uses' => 'ReceiptsToBanksController@postUndelete',
        'as' => 'receipts-banks.undelete'
    ]);
    Route::resource('receipts-banks', 'ReceiptsToBanksController', ['except' => ['edit']]);

    /**
     * Ruta para cobros
     */
    Route::get('charges/receipts-and-properties', [
        'uses' => 'ChargesController@getReceiptsAndProperties',
        'as' => 'charges.receipts_and_properties'
    ]);
    Route::post('charges/undo/{id}', [
        'uses' => 'ChargesController@postUndelete',
        'as' => 'charges.undelete'
    ]);
    Route::resource('charges', 'ChargesController', ['except' => ['show']]);
});

/**
 * Rutas para módulo Correo
 */
Route::group(['namespace' => 'Common', 'middleware' => ['auth', 'user_access:access_mail', 'user_connection']], function(){

    Route::resource('message', 'MessagesController', ['except' => ['show', 'index', 'update', 'edit', 'destroy']]);
    Route::get('received-messages', [
        'uses' => 'MessagesController@received',
        'as'   => 'received.messages'
    ]);
    Route::get('sent-messages', [
        'uses' => 'MessagesController@sent',
        'as'   => 'sent.messages'
    ]);
    Route::get('show-sent-messages/{id}', [
        'uses' => 'MessagesController@showSent',
        'as'   => 'show.sent.messages'
    ]);
    Route::get('show-received-messages/{id}', [
        'uses' => 'MessagesController@showReceived',
        'as'   => 'show.received.messages'
    ]);
    Route::get('delete-received-message/{id}', [
        'uses' => 'MessagesController@destroyReceived',
        'as'   => 'delete.received.message'
    ]);
    Route::get('delete-sent-message/{id}', [
        'uses' => 'MessagesController@destroySent',
        'as'   => 'delete.sent.message'
    ]);
    Route::get('download-message-file/{fileName}', [
        'uses' => 'MessagesController@download',
        'as'   => 'download.message.file'
    ]);

    /**
     * Text message
     */
    Route::get('text-messages/create', [
        'uses' => 'TextMessageController@create',
        'as'   => 'text.messages.create'
    ]);

    Route::post('text-messages/store', [
        'uses' => 'TextMessageController@store',
        'as'   => 'text.messages.store'
    ]);

    Route::get('sent-text-messages', [
        'uses' => 'TextMessageController@sent',
        'as'   => 'sent.text.messages'
    ]);
});

/**
 * Rutas para módulo Informes
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'user_access:access_reports', 'user_connection']], function(){
    Route::group(['prefix' => 'report'], function () {
        // Dossier
        Route::get('/dossier', ['as' => 'report.dossier', 'uses' => 'ReportController@dossier']);
        Route::get('/view-report-dossier', ['as' => 'report.viewdossier', 'uses' => 'ReportController@dossierViewReport']);
        Route::get('/export-dossier-pdf', ['as' => 'report.dossier-pdf', 'uses' => 'ReportController@dossierExportPdf']);
        Route::get('/export-dossier-excel', ['as' => 'report.dossier-excel', 'uses' => 'ReportController@dossierExportExcel']);

        // Liquidation Cons.

app/Models/Backend/AccountingAccount.php
<?php

namespace Edifalia\Models\Backend;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \Venturecraft\Revisionable\RevisionableTrait;

class AccountingAccount extends Model
{
    use SoftDeletes;
    use RevisionableTrait;

	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['code', 'title'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     *  Relationships
    */

    public function bankAccount()
    {
        return $this->hasOne('Edifalia\Models\Backend\BankAccount', 'accounting_account_id');
    }

    public function hasBankAccount()
    {
        return count($this->bankAccount) > 0;
    }
}

app/Models/Backend/BankAccount.php
<?php

namespace Edifalia\Models\Backend;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \Venturecraft\Revisionable\RevisionableTrait;

class BankAccount extends Model
{
    use SoftDeletes;
    use RevisionableTrait;

	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
    	'iban', 
        'code_a', 
        'code_b', 
        'code_c', 
        'code_d', 
        'code_e', 
        'sufix', 
        'bic', 
        'accounting_account_id'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     *  Relationships
    */
    public function accountingAccount()
    {
        return $this->belongsTo('Edifalia\Models\Backend\AccountingAccount', 'accounting_account_id');
    }


}

app/Models/Backend/Community.php
<?php

namespace Edifalia\Models\Backend;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \Venturecraft\Revisionable\RevisionableTrait;

class Community extends Model
{
	use SoftDeletes;
    use RevisionableTrait;

	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'code', 
        'name', 
        'address', 
        'nif', 
        'structure_year', 
        'elevator_numbers', 
        'platform_accounting',
        'longitude',
        'latitude',
        'notes', 
        'status_id', 
        'postal_code_id', 
        'president_id', 
        'banck_account_id',
        'accounting_account_id'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    public function hasProperties()
    {
        return count($this->properties) > 0;
    }

    public function office()
    {
        return $this->belongsTo(Offices::class);
    }

    public function hasOffice($office_id)
    {
        return ($this->office_id == $office_id) ? true : null;
    }

    public function getCodeNameAttribute(){
        return $this->code." - ".$this->name;
    }

    public function bankAccounts()
    {
        return $this->belongsToMany(
            'Edifalia\Models\Common\BankAccount', 'community_bank_accounts', 'community_id', 'bank_account_id'
        )->withTimestamps();
    }

    public function accountingAccounts()
    {
        return $this->belongsToMany(
            'Edifalia\Models\Common\AccountingAccount', 'community_accounting_accounts', 
            'community_id', 'accounting_account_id'
        )->withTimestamps();
    }

    public function properties()
    {
        return $this->hasMany('Edifalia\Models\Common\Property', 'community_id');
    }

    /**
     * The IssueReceipts that belong to the community.
     */
    public function issueReceipts()
    {
        return $this->belongsToMany('Edifalia\Models\IssueReceipt');
    }

    /**
     * Get the receiptDues for the Community.
     */
    public function receiptDues()
    {
        return $this->hasMany('Edifalia\Models\ReceiptDue');
    }
}

app/Models/Backend/ContractAccountingAccount.php
<?php

namespace Edifalia;

use Illuminate\Database\Eloquent\Model;

class ContractAccountingAccount extends Model
{
    //
}

app/Http/Controllers/Backend/ActionHistoryController.php
<?php

namespace Edifalia\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Edifalia\Http\Requests;
use Edifalia\Http\Controllers\Controller;
use Venturecraft\Revisionable\Revision;

class ActionHistoryController extends Controller
{
    public function getHistory()
    {
        $revisions = Revision::latest()->paginate(15);
        
        return view('backend.utilities.action_history.index')
            ->with('revisions', $revisions);
    }
}

app/Http/Controllers/Backend/BackupsController.php
<?php

namespace Edifalia\Http\Controllers\Backend;

use Edifalia\Http\Controllers\Controller;
use Maatwebsite\Excel\Facades\Excel;
use Edifalia\Http\Requests\Backup\BackupRequest;
use Chumper\Zipper\Zipper;
use Spatie\DbDumper\Databases\MySql;

class BackupsController extends Controller
{
    public function getIndex()
    {
        $tables[''] = trans('dashboard.fields.select_tables');
        $all= \DB::select('SHOW TABLES');
        $connection = config('database.default');
        $db_name = config('database.connections.'.$connection.'.database');
        $database = 'Tables_in_'.$db_name;
        foreach ($all as $table){
            $tables[$table->$database] = $table->$database;
        }
        $this->deleteFiles();
        return view('backend.utilities.backups.index')->with('tables', $tables);
    }

    public function postExport(BackupRequest $request)
    {
        $time = time();
        if ($request->get('format') == 'xls'){
            Excel::create('backup_'.$time, function($excel) use($request) {
                foreach ($request->get('tables') as $table){
                    $excel->sheet($table, function($sheet) use($table) {
                        $rows = \DB::table($table)->get();
                        $data = $rows->toJson();
                        $sheet->fromArray(json_decode($data, true));
                    });
                }
            })->export($request->get('format'));
        }
        elseif ($request->get('format') == 'csv'){

            foreach ($request->get('tables') as $table) {
                $rows = \DB::table($table)->get();
                $data = $rows->toJson();
                Excel::create($table.'_'.$time, function ($excel) use ($request, $data) {
                    $excel->sheet('sheet1', function ($sheet) use ($data) {
                        $sheet->fromArray(json_decode($data, true));
                    });
                })->store($request->get('format'));

            }
            $files = glob(storage_path('exports/*'.$time.'.csv'));
            $zip = new Zipper;
            $zip->make(storage_path('exports/backup_'.$time.'.zip'))->add($files);
            $zip->close();
            return response()->download(storage_path('exports/backup_'.$time.'.zip'));
        }
        else {
            MySql::create()->setDbName(config('database.connections.'.config('database.default').'.database'))
                ->setUserName(config('database.connections.'.config('database.default').'.username'))
                ->setPassword(config('database.connections.'.config('database.default').'.password'))
                ->includeTables($request->get('tables'))
                ->dumpToFile('backup_'.$time.'.sql');

            return response()->download(public_path('backup_'.$time.'.sql'));
        }
    }

    private function deleteFiles()
    {
        $filesXlsAndCsv = glob(storage_path('exports/*'));
        foreach ($filesXlsAndCsv as $file){
            unlink($file);
        }
        $filesSql = glob(public_path('*.sql'));
        foreach ($filesSql as $file){
            unlink($file);
        }
    }
}

resources/views/backend/receiptdue/index.blade.php
@extends('layouts.dashboard')

@if(!empty($data['breadcrumb_link']))
	@section('breadcrumb_link')
		{{ $data['breadcrumb_link'] }}
	@endsection
@endif

@if(!empty($data['breadcrumb_icon']))
	@section('breadcrumb_icon')
		{{ $data['breadcrumb_icon'] }}
	@endsection
@endif

@if(!empty($data['breadcrumb_title']))
	@section('breadcrumb_title')
		{{ $data['breadcrumb_title'] }}
	@endsection
@endif

@if(!empty($data['breadcrumb_subtitle']))
	@section('breadcrumb_subtitle')
		{{ $data['breadcrumb_subtitle'] }}
	@endsection
@endif

@if(!empty($data['breadcrumb_map']))
	@section('breadcrumb_map')
		{{ $data['breadcrumb_map'] }}
	@endsection
@endif

@section('breadcrumb_map')
    <li>
        <a href="{{ url('dashboard') }}">
            <i class="fa fa-dashboard"></i> @lang('dashboard.home')
        </a>
    </li>
    <li><a href="#">@lang('dashboard.mnu_management')</a></li>
    <li class="active">@lang('dashboard.mnu_quota_receipts')</li>
@endsection

@section('modals')
    @include('backend.partials.modals')
@endsection

@section('content')

	<div class="box box-default">
		<div class="box-header with-border">
			<div class="panel-title inline-block">
				<h5 class="box-title">
					<i class="glyphicon glyphicon-list-alt"></i>&#160;
					{{ $data['panel_title'] }}
				</h5>
			</div>
		</div>
		<div class="box-body">
			<div class="">
				<table class="table table-hover table-striped dt-responsive nowrap display dataTable" width="100%">
					@if(!empty($data['tbody']))
						<thead>
							<tr>
								<th>@lang('receipt_due.table_id')</th>
								<th>@lang('receipt_due.table_concept')</th>
								<th>@lang('receipt_due.table_amount')</th>
								<th>@lang('receipt_due.table_month')</th>
								<th>@lang('receipt_due.table_year')</th>
								<th class="text-center">@lang('common.lst_action_title')</th>
							</tr>
						</thead>
					@endif
					<tbody>
						@forelse($data['tbody'] as $tbody)
							<tr data-id="{{ $tbody['record_id'] }}" 
							data-rundo="{{route('receiptdues.undelete', $tbody['record_id'])}}">

								{!! $tbody['cols'] !!}
								<td class="col-xs-2 col-sm-2 col-md-2 col-lg-2 text-center">
									<div class="btn-group btn-group-xs">
	                                	<a data-toggle="tooltip" class="btn btn-info"
	                                   title="@lang('common.lst_act_show')"
	                                   href="{{route('receiptdues.show', $tbody['record_id'])}}">
	                                    <i class="fa fa-eye"></i></a>

	                                    <a data-toggle="tooltip" class="btn btn-info"
	                                   title="@lang('dashboard.buttons.edit')"
	                                   href="{{route('receiptdues.edit', $tbody['record_id'])}}">
	                                    <i class="fa fa-pencil-square-o"></i></a>

		                                <a data-toggle="tooltip" class="btn btn-info delete_record"
	                                   title="@lang('dashboard.buttons.delete')"
	                                   href="{{route($tbody['url_delete'], $tbody['record_id'])}}">
	                                    <i class="fa fa-trash-o"></i></a>
		                                
		                            </div>
								</td>
							</tr>
						@empty
						    <div class="alert alert-warning">
						        <h4><i class="icon fa fa-warning"></i> @lang('dashboard.messages.notice')</h4>
						        @lang('dashboard.messages.no_stored_records')
						    </div>
						@endforelse
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">
			<a data-toggle="tooltip" class="btn btn-primary col-xs-12 col-sm-12 col-md-1 col-lg-1 pull-right"
               title="@lang('common.lst_new_record')"
               href="{{ $data['url_new'] }}">
                <i class="fa fa-plus"></i> @lang('common.lst_new_record')</a>
		</div>
	</div>
@endsection

@section('scripts')
    {{-- Backend scripts  --}}
    {!! Html::script('js/code01.js') !!}
@endsection

resources/views/backend/receiptdue/view.blade.php
@extends('layouts.dashboard')

@if(!empty($data['breadcrumb_link']))
	@section('breadcrumb_link')
		{{ $data['breadcrumb_link'] }}
	@endsection
@endif

@if(!empty($data['breadcrumb_icon']))
	@section('breadcrumb_icon')
		{{ $data['breadcrumb_icon'] }}
	@endsection
@endif

@if(!empty($data['breadcrumb_title']))
	@section('breadcrumb_title')
		{{ $data['breadcrumb_title'] }}
	@endsection
@endif

@if(!empty($data['breadcrumb_subtitle']))
	@section('breadcrumb_subtitle')
		{{ $data['breadcrumb_subtitle'] }}
	@endsection
@endif

@if(!empty($data['breadcrumb_map']))
	@section('breadcrumb_map')
		{{ $data['breadcrumb_map'] }}
	@endsection
@endif

@section('breadcrumb_map')
    <li>
        <a href="{{ url('dashboard') }}">
            <i class="fa fa-dashboard"></i> @lang('dashboard.home')
        </a>
    </li>
    <li><a href="#">@lang('dashboard.mnu_management')</a></li>
    <li class="active">@lang('dashboard.mnu_quota_receipts')</li>
@endsection

@section('content')

<div class="box box-info">
		<div class="box-header with-border">
			<div class="panel-title inline-block">
				<h5 class="box-title">
					<i class="glyphicon glyphicon-list-alt"></i>&#160;
					{{ $data['panel_title'] }}
				</h5>
				<div class="btn-group btn-group-sm pull-right">
					<a data-toggle="tooltip" class="btn btn-primary" title="@lang('dashboard.buttons.back')" 
					   href="{{ $data['breadcrumb_link'] }}">
					    <i class="fa fa-reply"></i>
					</a>
					<a data-toggle="tooltip" class="btn btn-primary" title="@lang('dashboard.buttons.new')" 
					   href="{{ $data['url_new'] }}">
					    <i class="fa fa-plus"></i>
					</a>
				</div>
			</div>
		</div>
		<div class="box-body">

			<div class="row">

				<div class="col-sm-12 col-md-12 col-lg-12 form-group">
					<label class="col-sm-1 control-label" for="text">Comunidad</label>
					<div class="col-sm-3">{{ $receiptdue[0]->community_name }}
					</div>

					<label class="col-sm-2 control-label" for="text">Concepto de facturación</label>
					<div class="col-sm-3">{{ $receiptdue[0]->invoicing_concept_name }}
					</div>
				</div>
			</div>

			<br><br><br>
			<table class="table table-striped table-hover">
				<thead>
				<tr>
					<td colspan="4" align="right"><strong>TOTAL ...</strong></td>
					<td width="5%" style="background-color: #eee;">{{ $receiptdue[0]->total_amount }}
					</td>
					<td width="5%" id="td_month" style="background-color: #eee; ">{{ $receiptdue[0]->month }}
					</td>
					<td width="5%" id="td_year" style="background-color: #eee; ">{{ $receiptdue[0]->year }}
					</td>
				</tr>
				<tr>
					<td width="5%"><strong>@lang('receipt_due.table_id')</strong></td>
					<td><strong>@lang('receipt_due.table_bloq')</strong></td>
					<td><strong>@lang('receipt_due.table_property')</strong></td>
					<td><strong>@lang('receipt_due.table_payer')</strong></td>
					<td><strong>@lang('receipt_due.table_amount')</strong></td>
					<td width="5%"><strong>@lang('receipt_due.table_month')</strong></td>
					<td width="5%"><strong>@lang('receipt_due.table_year')</strong></td>
				</tr>
				</thead>
				<tbody id="receiptdue_body">
					@foreach ($receiptdueItem as $row)
					<tr>
						<td>{{ $row->id }}</td>
						<td>{{ $row->building_number }}</td>
						<td>{{ $row->property_number }}</td>
						<td>{{ $row->first_name." ".$row->last_name }}</td>
						<td>{{ $row->coefficient }}</td>
						<td>{{ $receiptdue[0]->month }}</td>
						<td>{{ $receiptdue[0]->year }}</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
		<div class="box-footer">
			<a data-toggle="tooltip" class="btn btn-primary col-xs-12 col-sm-12 col-md-1 col-lg-1 pull-right"
           title="@lang('common.lst_act_edit')"
           href="{{ route('receiptdues.edit', $receiptdue[0]->id) }}">
            <i class="fa fa-pencil-square-o"></i> @lang('common.lst_act_edit')</a>
		</div>
	</div>
@endsection