routes/web.php
<?php
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
/*Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::post('register', 'Auth\RegisterController@register');*/

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/', 'HomeController@index');

/**
 * Rutas para módulo Datos
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'user_access:access_data', 'user_connection']], function(){
    /**
     * Rutas de comunidades
     */
    Route::resource('community', 'CommunitiesController');

    /**
     * Rutas de propiedades
     */
    Route::resource('property', 'PropertiesController', ['except' => ['show']]);

    /**
     * Ruta person
     */
    Route::resource('person', 'PersonsController');

    /**
     * Rutas de Proveedores
     */
    Route::resource('supplier', 'SuppliersController');

    /**
     * Ruta para la gestión de coeficientes
     */
    Route::resource('coefficient', 'CoefficientController', [
        'except' => ['create', 'store', 'show', 'destroy']
    ]);

    /**
     * Ruta de Contratos
     */
    Route::resource('contract', 'ContractsController');

    /**
     * Ruta de códigos postales
     */
    Route::resource('postal-code', 'PostalCodesController');
    Route::get('postal-code/get-data/{id}', 'PostalCodesController@getData');
});

/**
 * Rutas para módulo Gestión
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'user_access:access_management', 'user_connection']], function(){
    /**
     * Ruta de documents
     */
    Route::post('pages/undo/{id}', [
        'uses' => 'PagesController@postUndelete',
        'as' => 'pages.undelete'
    ]);
    Route::resource('pages', 'PagesController', ['except' => ['show']]);

    Route::post('tags/undo/{id}', [
        'uses' => 'TagsController@postUndelete',
        'as' => 'tags.undelete'
    ]);
    Route::resource('tags', 'TagsController', ['except' => ['show']]);

    Route::post('documents/undo/{id}', [
        'uses' => 'DocumentsController@postUndelete',
        'as' => 'documents.undelete'
    ]);
    Route::resource('documents', 'DocumentsController');

    /**
     * Ruta de templates
     */
    Route::post('models/undo/{id}', [
        'uses' => 'ModelsController@postUndelete',
        'as' => 'models.undelete'
    ]);
    Route::resource('models', 'ModelsController', ['except' => ['show']]);

    Route::post('templates/undo/{id}', [
        'uses' => 'TemplatesController@postUndelete',
        'as' => 'templates.undelete'
    ]);
    Route::resource('templates', 'TemplatesController', ['except' => ['show']]);

    /**
     * Ruta de incidences
     */
    Route::post('communicator-types/undo/{id}', [
        'uses' => 'CommunicatorTypesController@postUndelete',
        'as' => 'communicator-types.undelete'
    ]);
    Route::resource('communicator-types', 'CommunicatorTypesController', ['except' => ['show']]);

    Route::post('receptions/undo/{id}', [
        'uses' => 'ReceptionsController@postUndelete',
        'as' => 'receptions.undelete'
    ]);
    Route::resource('receptions', 'ReceptionsController', ['except' => ['show']]);

    Route::post('reasons/undo/{id}', [
        'uses' => 'ReasonsController@postUndelete',
        'as' => 'reasons.undelete'
    ]);
    Route::resource('reasons', 'ReasonsController', ['except' => ['show']]);

    Route::post('sectors/undo/{id}', [
        'uses' => 'SectorsController@postUndelete',
        'as' => 'sectors.undelete'
    ]);
    Route::resource('sectors', 'SectorsController', ['except' => ['show']]);

    Route::get('incidences/communities', [
        'uses' => 'IncidencesController@getCommunities',
        'as' => 'incidences.communities'
    ]);

    Route::post('incidences/undo/{id}', [
        'uses' => 'IncidencesController@postUndelete',
        'as' => 'incidences.undelete'
    ]);
    Route::resource('incidences', 'IncidencesController');

    /**
     * Ruta de presupuestos
     */
    Route::post('invoicing-concepts/undo/{id}', [
        'uses' => 'InvoicingConceptsController@postUndelete',
        'as' => 'invoicing-concepts.undelete'
    ]);
    Route::resource('invoicing-concepts', 'InvoicingConceptsController', ['except' => ['show']]);

    Route::get('budgets/community-properties', [
        'uses' => 'BudgetsController@getCommunityProperties',
        'as' => 'budgets.properties'
    ]);
    Route::get('budgets/data', [
        'uses' => 'BudgetsController@getBudgetData',
        'as' => 'budgets.data'
    ]);
    Route::post('budgets/undo/{id}', [
        'uses' => 'BudgetsController@postUndelete',
        'as' => 'budgets.undelete'
    ]);
    Route::resource('budgets', 'BudgetsController', ['except' => ['show']]);

    /**
     * Ruta de readings
     */
    Route::post('rates/undo/{id}', [
        'uses' => 'RatesController@postUndelete',
        'as' => 'rates.undelete'
    ]);
    Route::resource('rates', 'RatesController', ['except' => ['show']]);

    Route::get('readings/data', [
        'uses' => 'ReadingsController@getReadingData',
        'as' => 'readings.data'
    ]);
    Route::get('readings/community-properties', [
        'uses' => 'ReadingsController@getCommunityProperties',
        'as' => 'readings.properties'
    ]);
    Route::post('readings/undo/{id}', [
        'uses' => 'ReadingsController@postUndelete',
        'as' => 'readings.undelete'
    ]);
    Route::resource('readings', 'ReadingsController', ['except' => ['show']]);

    /**
     * Ruta de Cuotas de recibos
     */
    Route::get('receiptdues/getProperties', 'ReceiptDuesController@getProperties');
    Route::get('receiptdues/getReceipDueLastMonth', 'ReceiptDuesController@getReceipDueLastMonth');
    Route::post('receiptdues/postUndelete/{id}', [
        'uses' => 'ReceiptDuesController@postUndelete',
        'as' => 'receiptdues.undelete'
    ]);
    Route::resource('receiptdues', 'ReceiptDuesController');

    /**
     * Ruta para emision de recibos
     */
    Route::post('issue-receipts/undo/{id}', [
        'uses' => 'IssueReceiptsController@postUndelete',
        'as' => 'issue-receipts.undelete'
    ]);
    Route::resource('issue-receipts', 'IssueReceiptsController', ['except' => ['edit']]);

    /**
     * Ruta para recibos a bancos
     */
    Route::post('receipts-banks/undo/{id}', [
        'uses' => 'ReceiptsToBanksController@postUndelete',
        'as' => 'receipts-banks.undelete'
    ]);
    Route::resource('receipts-banks', 'ReceiptsToBanksController', ['except' => ['edit']]);

    /**
     * Ruta para cobros
     */
    Route::get('charges/receipts-and-properties', [
        'uses' => 'ChargesController@getReceiptsAndProperties',
        'as' => 'charges.receipts_and_properties'
    ]);
    Route::post('charges/undo/{id}', [
        'uses' => 'ChargesController@postUndelete',
        'as' => 'charges.undelete'
    ]);
    Route::resource('charges', 'ChargesController', ['except' => ['show']]);
});

/**
 * Rutas para módulo Correo
 */
Route::group(['namespace' => 'Common', 'middleware' => ['auth', 'user_access:access_mail', 'user_connection']], function(){

    Route::resource('message', 'MessagesController', ['except' => ['show', 'index', 'update', 'edit', 'destroy']]);
    Route::get('received-messages', [
        'uses' => 'MessagesController@received',
        'as'   => 'received.messages'
    ]);
    Route::get('sent-messages', [
        'uses' => 'MessagesController@sent',
        'as'   => 'sent.messages'
    ]);
    Route::get('show-sent-messages/{id}', [
        'uses' => 'MessagesController@showSent',
        'as'   => 'show.sent.messages'
    ]);
    Route::get('show-received-messages/{id}', [
        'uses' => 'MessagesController@showReceived',
        'as'   => 'show.received.messages'
    ]);
    Route::get('delete-received-message/{id}', [
        'uses' => 'MessagesController@destroyReceived',
        'as'   => 'delete.received.message'
    ]);
    Route::get('delete-sent-message/{id}', [
        'uses' => 'MessagesController@destroySent',
        'as'   => 'delete.sent.message'
    ]);
    Route::get('download-message-file/{fileName}', [
        'uses' => 'MessagesController@download',
        'as'   => 'download.message.file'
    ]);

    /**
     * Text message
     */
    Route::get('text-messages/create', [
        'uses' => 'TextMessageController@create',
        'as'   => 'text.messages.create'
    ]);

    Route::post('text-messages/store', [
        'uses' => 'TextMessageController@store',
        'as'   => 'text.messages.store'
    ]);

    Route::get('sent-text-messages', [
        'uses' => 'TextMessageController@sent',
        'as'   => 'sent.text.messages'
    ]);
});

/**
 * Rutas para módulo Informes
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'user_access:access_reports', 'user_connection']], function(){
    Route::group(['prefix' => 'report'], function () {
        // Dossier
        Route::get('/dossier', ['as' => 'report.dossier', 'uses' => 'ReportController@dossier']);
        Route::get('/view-report-dossier', ['as' => 'report.viewdossier', 'uses' => 'ReportController@dossierViewReport']);
        Route::get('/export-dossier-pdf', ['as' => 'report.dossier-pdf', 'uses' => 'ReportController@dossierExportPdf']);
        Route::get('/export-dossier-excel', ['as' => 'report.dossier-excel', 'uses' => 'ReportController@dossierExportExcel']);

        // Liquidation Cons.

app/Http/Controllers/Backend/DocumentsController.php
<?php

namespace Edifalia\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Edifalia\Http\Controllers\Controller;
use Edifalia\Models\Document;
use Edifalia\Http\Requests\Document\CreateRequest;
use Edifalia\Http\Requests\Document\EditRequest;
use Illuminate\Support\Facades\Session;
use Edifalia\Repositories\UploadFileRepository;
use Edifalia\Models\Tag;
use Illuminate\Support\Facades\Gate;
use Edifalia\Repositories\DocumentRepository;

class DocumentsController extends Controller
{
    protected $documentRepo;

    public function __construct(DocumentRepository $documentRepo)
    {
        $this->documentRepo = $documentRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Gate::allows('admin')){
            $documents = $this->documentRepo->getAll();
        } else if(Gate::allows('employee')){
            $documents = $this->documentRepo->getEmployeeDocuments();
        }
        return view('backend.management.documents.index')
            ->with('documents', $documents);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $header = [
            'route' => 'documents.store',
            'method' => 'POST',
            'role' => 'form',
            'files' => 'true'
        ];
        return view('backend.management.documents.create_or_edit')->with('header', $header)
            ->with('title', trans('dashboard.titles.add_doc'))->with('new', true);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  $up
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request, UploadFileRepository $up)
    {
        if($this->documentRepo->checkCommunity($request->get('community_id'))) {
            if (!$up->uploadFile($request->document, 'local_documents', $this->getNewDirName($request->tag_id))) {
                Session::flash('message', [
                    'alert' => 'danger',
                    'text' => $up->getErrorMessage(),
                ]);
                return back()->withInput();
            }
            $this->documentRepo->saveNewWithUserAndDoc($request, $up->getFileName());
        } else {
            return redirect()->route('documents.create');
        }

        Session::flash('message', [
            'alert' => 'success',
            'text' => trans('dashboard.messages.created')
        ]);

        return redirect()->route('documents.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $document = $this->documentRepo->find($id);

        if (is_null($document) || Gate::denies('has', $document->user_id))
            return redirect()->route('documents.index');

        return view('backend.management.documents.show')->with('document', $document);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $document = $this->documentRepo->find($id);
        if (is_null($document) || Gate::denies('has', $document->user_id))
            return redirect()->route('documents.index');

        $header = [
            'route' => ['documents.update', $document->id],
            'method' => 'PUT',
            'role' => 'form',
            'files' => 'true'
        ];

        return view('backend.management.documents.create_or_edit')->with('header', $header)
            ->with('title', trans('dashboard.titles.edit_doc'))
            ->with('document', $document)->with('edit', true);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditRequest $request, UploadFileRepository $up, $id)
    {
        $document = $this->documentRepo->find($id);
        if (is_null($document) || Gate::denies('has', $document->user_id))
            return redirect()->route('documents.index');

        if ($this->documentRepo->checkCommunity($request->get('community_id'))) {
            $currentDocument = strstr($document->document, '/'); // -> with '/'
            $currentDir = strstr($document->document, '/', true); // <- without '/'
            $newDir = $this->getNewDirName($request->tag_id);

            if ($request->hasFile('document')) {
                if (!$up->uploadFile($request->document, 'local_documents', $newDir)) {
                    Session::flash('message', [
                        'alert' => 'danger',
                        'text' => $up->getErrorMessage(),
                    ]);
                    return back()->withInput();
                }
                $up->deleteFile($document->document, 'local_documents');
                $document->document = $up->getFileName();
            } elseif ($currentDir != $newDir) {
                if (\Storage::disk('local_documents')->exists($document->document)) {
                    \Storage::disk('local_documents')->move($document->document, $newDir . $currentDocument);
                    $up->deleteFile($document->document, 'local_documents');
                    $document->document = $newDir . $currentDocument;
                }
            }
            $this->documentRepo->updateDocument($document, $request);
        } else {
            return redirect()->route('documents.edit', $document->id);
        }

        Session::flash('message', [
            'alert' => 'success',
            'text' => trans('dashboard.messages.updated')
        ]);
        return redirect()->route('documents.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if ($request->ajax()) {
            $document = $this->documentRepo->find($id);
            if (!is_null($document) && Gate::allows('has', $document->user_id)){
                $this->documentRepo->delete($document);
                $array = [
                    'data' => true,
                    'id' => $id,
                    'message' => trans('dashboard.messages.deleted'),
                    'undo' => trans('dashboard.buttons.undo')
                ];
            } else {
                $array = [
                    'data' => false,
                    'message' => trans('dashboard.messages.error')
                ];
            }
            return response()->json($array);
        }
    }

    public function postUndelete(Request $request, $id)
    {
        if($request->ajax()){
            $document = $this->documentRepo->recordInTrash($id);
            if (!is_null($document)){
                $this->documentRepo->restore($document);
                $array = ['data' => true, 'id' => $id];
            } else {
                $array = [
                    'data' => false,
                    'message' => trans('dashboard.messages.error')
                ];
            }
            return response()->json($array);
        }
    }

    private function getNewDirName($id)
    {
        $tag = Tag::find($id);
        $dir = str_slug($tag->name, '_');
        return $dir;
    }
}

resources/views/backend/management/documents/create_or_edit.blade.php
@extends('layouts.dashboard')

@section('breadcrumb_title')
    @lang('dashboard.mnu_management')
@endsection

@section('breadcrumb_subtitle')
    {{$title}}
@endsection

@section('breadcrumb_map')
    <li>
        <a href="{{ url('dashboard') }}">
            <i class="fa fa-dashboard"></i> @lang('dashboard.home')
        </a>
    </li>
    <li><a href="#">@lang('dashboard.mnu_management')</a></li>
    <li class="active">@lang('dashboard.mnu_post_docs')</li>
@endsection

@section('content')
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">@lang('dashboard.mnu_management')</h3>
            <div class="btn-group btn-group-sm pull-right">
            <a data-toggle="tooltip" class="btn btn-primary"
               title="@lang('dashboard.buttons.back')"
               href="{{route('documents.index')}}">
                <i class="fa fa-reply"></i></a>
                @if(isset($edit))
                    <a data-toggle="tooltip" class="btn btn-primary"
                       title="@lang('dashboard.buttons.new')"
                       href="{{route('documents.create')}}">
                        <i class="fa fa-plus"></i></a>
                @endif
            </div>
        </div>

        @inject('pages', 'Edifalia\Services\Pages')
        @inject('tags', 'Edifalia\Services\Tags')
        @inject('owners', 'Edifalia\Services\Persons')
        @inject('communities', 'Edifalia\Services\Communities')

        @if(isset($new))
            {!! Form::open($header) !!}
        @elseif(isset($edit))
            {!! Form::model($document, $header) !!}
        @endif
            <div class="box-body">
                @if(!count($pages->get()) || !count($tags->get()))
                    <div class="alert alert-warning">
                        <h4><i class="icon fa fa-warning"></i> @lang('dashboard.messages.notice')</h4>
                        @lang('dashboard.messages.no_pages_tags')
                    </div>
                @endif

                @include('backend.partials.messages')
                @include('backend.management.documents.fields')
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info">
                    <i class="fa fa-save"></i>
                    @if(isset($new)) @lang('dashboard.buttons.save') @elseif(isset($edit))
                        @lang('dashboard.buttons.update')
                    @endif
                </button>
            </div>
        {!! Form::close() !!}
    </div>
@endsection

@section('styles')
    {{-- bootstrap datepicker --}}
    {!! Html::style('static/plugins/datepicker/datepicker3.css') !!}
    {{-- Select2 --}}
    {!! Html::style('static/plugins/select2/select2.min.css') !!}
@endsection

@section('scripts')
    {{-- bootstrap datepicker --}}
    {!! Html::script('static/plugins/datepicker/bootstrap-datepicker.js') !!}
    {{-- Select2 --}}
    {!! Html::script('static/plugins/select2/select2.full.min.js') !!}
    <script>
        $(document).ready(function(){
            $(".select2").select2();

            $("#datepicker").datepicker();

            /*$("#datepicker").datepicker({
                autoclose: true,
                minDate: new Date(2007, 1 - 1, 1),
                dateFormat: "yy-mm-dd"
            });*/
        });
    </script>
@endsection

resources/views/backend/management/documents/fields.blade.php
<div class="row">
    <div class="form-group col-md-6 {{ $errors->has('document') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.document')) !!}
        {!! Form::file('document') !!}
        @if(isset($document))
            {!! Form::label(trans('dashboard.fields.current_doc')) !!}
            @if($document->existsFile())
                <a href="{{asset('docs/'.$document->document)}}" target="_blank">
                    {{$document->document}}
                </a>
            @else
                <p class="text-danger">
                    <i class="fa fa-warning"></i>
                    @lang('dashboard.messages.no_doc')
                </p>
            @endif
        @endif
    </div>
    <div class="form-group col-md-6 {{ $errors->has('community_id') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.community')) !!}
        {!! Form::select('community_id', Auth::user()->can('admin') ? $communities->all() : $communities->ofEmployee(), null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="row">
    <div class="form-group col-md-6 {{ $errors->has('title') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.title')) !!}
        {!! Form::text('title', null, [
            'class' => 'form-control',
            'placeholder' => trans('dashboard.fields.title'),
            'required' => true])
        !!}
    </div>
    <div class="form-group col-md-6 {{ $errors->has('publication_date') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.publication_date')) !!}
        <div class="input-group date">
            <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
            </div>
            {!! Form::text('publication_date', null, [
                'class' => 'form-control pull-right',
                'placeholder' => trans('dashboard.fields.publication_date'),
                'id' => 'datepicker',
                'required' => true])
            !!}
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group col-md-4 {{ $errors->has('page_id') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.page')) !!}
        {!! Form::select('page_id', $pages->get(),null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group col-md-4 {{ $errors->has('tag_id') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.tag')) !!}
        {!! Form::select('tag_id', $tags->get(),null, ['class' => 'form-control']) !!}
        {{ link_to_route('tags.create', $title = trans('dashboard.titles.add_new_tag')) }}
    </div>
    <div class="form-group col-md-4 {{ $errors->has('owners') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.permissions')) !!}
        @if(isset($new))
            {!! Form::select('owners[]', $owners->get(),null, [
                'class' => 'form-control select2',
                'multiple' => true,
                'data-placeholder' => trans('dashboard.fields.select_owner') ])
            !!}
        @elseif(isset($edit))
            <select name="owners[]" class="form-control select2" multiple="multiple" data-placeholder="@lang('dashboard.fields.select_owner')">
            @foreach($owners->get() as $key => $person)
                {{$key}}
                @if($document->personSaved($key))
                    <option selected value="{{$key}}">{{$person}}</option>
                @else
                    <option value="{{$key}}">{{$person}}</option>
                @endif
            @endforeach
            </select>
        @endif
        <p class="help-block">@lang('dashboard.fields.doc_public')</p>
    </div>
</div>

resources/views/backend/management/documents/index.blade.php
@extends('layouts.dashboard')

@section('breadcrumb_title')
    @lang('dashboard.mnu_management')
@endsection

@section('breadcrumb_subtitle')
    @lang('dashboard.titles.doc_list')
@endsection

@section('breadcrumb_map')
    <li>
        <a href="{{ url('dashboard') }}">
            <i class="fa fa-dashboard"></i> @lang('dashboard.home')
        </a>
    </li>
    <li><a href="#">@lang('dashboard.mnu_management')</a></li>
    <li class="active">@lang('dashboard.mnu_post_docs')</li>
@endsection

@section('modals')
    @include('backend.partials.modals')
@endsection

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">@lang('dashboard.mnu_post_docs')</h3>
        </div>
        <div class="box-body table-responsive">
            <table class="table table-hover">
                @if($documents->count())
                    <tr>
                        <th>@lang('dashboard.tables.registration_date')</th>
                        <th>@lang('dashboard.tables.publication_date')</th>
                        <th>@lang('dashboard.tables.title')</th>
                        <th>@lang('dashboard.tables.page')</th>
                        <th>@lang('dashboard.tables.tag')</th>
                        <th>@lang('dashboard.tables.actions')</th>
                    </tr>
                @endif
                @forelse($documents as $document)
                    <tr data-id="{{$document->id}}"
                        data-rundo="{{route('documents.undelete', $document->id)}}">
                        <td>{{$document->created_at->format('d/m/Y')}}</td>
                        <td>{{$document->publication_date}}</td>
                        <td>{{$document->title}}</td>
                        <td>{{$document->page->name}}</td>
                        <td>{{$document->tag->name}}</td>
                        <td>
                            <div class="btn-group btn-group-xs">
                                <a data-toggle="tooltip" class="btn btn-info"
                                   title="@lang('dashboard.buttons.info')"
                                   href="{{route('documents.show', $document->id)}}">
                                    <i class="fa fa-eye"></i></a>

                                <a data-toggle="tooltip" class="btn btn-info"
                                   title="@lang('dashboard.buttons.edit')"
                                   href="{{route('documents.edit', $document->id)}}">
                                    <i class="fa fa-pencil-square-o"></i></a>

                                <a data-toggle="tooltip" class="btn btn-info delete_record"
                                   title="@lang('dashboard.buttons.delete')"
                                   href="{{route('documents.destroy', $document->id)}}">
                                    <i class="fa fa-trash-o"></i></a>
                            </div>
                        </td>
                    </tr>
                @empty
                    <div class="alert alert-warning">
                        <h4><i class="icon fa fa-warning"></i> @lang('dashboard.messages.notice')</h4>
                        @lang('dashboard.messages.no_stored_records')
                    </div>
                @endforelse
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            {{$documents->links()}}
            <a data-toggle="tooltip" class="btn btn-primary pull-right"
               title="@lang('dashboard.buttons.new')"
               href="{{route('documents.create')}}">
                <i class="fa fa-plus"></i> @lang('dashboard.buttons.new')</a>
        </div>
        <!-- /.box-footer-->
    </div>
@endsection

@section('scripts')
    {{-- Backend scripts  --}}
    {!! Html::script('js/code01.js') !!}
@endsection