routes/web.php
        Route::group(['prefix' => 'meeting'], function () {
            Route::get('/list{format?}', ['as' => 'report.meeting', 'uses' => 'ReportController@meeting']);
            Route::get('/show/{id}', ['as' => 'meeting.show', 'uses' => 'ReportController@meetingShow']);
            Route::get('/create', ['as' => 'meeting.create', 'uses' => 'ReportController@meetingCreate']);
            Route::post('/load', ['as' => 'meeting.load', 'uses' => 'ReportController@meetingLoad']);
            Route::get('/view-assistant', ['as' => 'meeting.assistant', 'uses' => 'ReportController@meetingAssistant']);
            Route::get('/export-meeting-pdf/{id?}', ['as' => 'meeting.export-pdf', 'uses' => 'ReportController@meetingExportPdf']);
            Route::get('/export-meeting-excel/{id?}', ['as' => 'meeting.export-excel', 'uses' => 'ReportController@meetingExportExcel']);
            Route::get('/remove', ['as' => 'meeting.remove', 'uses' => 'ReportController@meetingRemove']);
        });

        // Meeting
        Route::group(['prefix' => 'economic'], function () {
            Route::get('/for-group-account', ['as' => 'economic.account', 'uses' => 'ReportEconomicController@forAccount']);
            Route::get('/for-group-account-excel', ['as' => 'economic.account-excel', 'uses' => 'ReportEconomicController@forAccountExcel']);

            Route::get('/for-movement-detail', ['as' => 'economic.movement', 'uses' => 'ReportEconomicController@forMovement']);
            Route::get('/for-movement-detail-excel', ['as' => 'economic.movement-excel', 'uses' => 'ReportEconomicController@forMovementExcel']);

            Route::get('/for-clasification-group', ['as' => 'economic.clasification-group', 'uses' => 'ReportEconomicController@forClasification']);
            Route::get('/for-clasification-group-excel', ['as' => 'economic.clasification-group-excel', 'uses' => 'ReportEconomicController@forClasificationExcel']);
            
            Route::get('/for-month', ['as' => 'economic.month', 'uses' => 'ReportEconomicController@forMonth']);
            Route::get('/for-month-pdf', ['as' => 'economic.month-pdf', 'uses' => 'ReportEconomicController@forMonthPdf']);
            Route::get('/for-month-excel', ['as' => 'economic.month-excel', 'uses' => 'ReportEconomicController@forMonthExcel']);

            Route::get('/for-property', ['as' => 'economic.property', 'uses' => 'ReportEconomicController@forProperty']);
            Route::get('/for-property-excel', ['as' => 'economic.property-excel', 'uses' => 'ReportEconomicController@forPropertyExcel']);
            
            Route::get('/for-total', ['as' => 'economic.total', 'uses' => 'ReportEconomicController@forTotal']);
            Route::get('/for-total-excel', ['as' => 'economic.total-excel', 'uses' => 'ReportEconomicController@forTotalExcel']);

            Route::get('/for-supplier-payment', ['as' => 'economic.payment-supplier', 'uses' => 'ReportEconomicController@forSupplierPayment']);
            Route::get('/for-supplier-payment-excel', ['as' => 'economic.payment-supplier-excel', 'uses' => 'ReportEconomicController@forSupplierPaymentExcel']);

            Route::get('/for-supplier-pending', ['as' => 'economic.supplier-pending', 'uses' => 'ReportEconomicController@forSupplierPending']);
            Route::get('/for-supplier-pending-excel', ['as' => 'economic.supplier-pending-excel', 'uses' => 'ReportEconomicController@forSupplierPendingExcel']);
            
            Route::get('/receipt', ['as' => 'economic.receipt', 'uses' => 'ReportEconomicController@forReceipt']);            
            Route::get('/receipt-export-pdf', ['as' => 'economic.receipt-pdf', 'uses' => 'ReportEconomicController@forReceiptExportPdf']);            
            Route::get('/receipt-export-excel', ['as' => 'economic.receipt-excel', 'uses' => 'ReportEconomicController@forReceiptExportExcel']);
        });

        // Data Generica Para Reportes
        Route::group(['prefix' => 'generic-data'], function () {
            Route::get('/community', ['as' => 'gereric.community', 'uses' => 'GenericDataController@getCommunity']);
            Route::get('/get-property-for-community', ['as' => 'generic-property', 'uses' => 'GenericDataController@getPropertyForCommunity']);
            Route::post('/get-community-for-id', ['as' => 'generic-property', 'uses' => 'GenericDataController@getCommunityForId']);
            Route::get('/get-meeting-for-community', ['as' => 'generic-meeting', 'uses' => 'GenericDataController@getMeetingForCommunity']);
            Route::get('/get-budgets-for-community', ['as' => 'generic-budget', 'uses' => 'GenericDataController@getBudgetForCommunity']);
            Route::get('/get-reading-for-community', ['as' => 'generic-reading', 'uses' => 'GenericDataController@getReadingForCommunity']);
            Route::get('/get-meeting-control', ['as' => 'generic-meeting-control', 'uses' => 'GenericDataController@getMeetingControl']);
            Route::get('/get-reading-for-id', ['as' => 'generic-reading-id', 'uses' => 'GenericDataController@getReadingForId']);
            Route::get('/get-months', ['as' => 'generic.get-months', 'uses' => 'GenericDataController@getMonths']);
        });

        Route::group(['prefix' => 'control'], function () {
            Route::get('/list{format?}', ['as' => 'report.controls', 'uses' => 'ReportController@controlIndex']);            
            Route::get('/create', ['as' => 'control.create', 'uses' => 'ReportController@controlCreate']);            
            Route::post('/create-post', ['as' => 'control.create', 'uses' => 'ReportController@controlCreate']);
            Route::get('/remove', ['as' => 'control.remove', 'uses' => 'ReportController@controlRemove']);
        });        
    });
});

/**
 * Rutas para módulo Contabilidad
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'user_access:access_accounting', 'user_connection']], function(){

});

/**
 * Rutas solo para administradores
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'admin', 'user_connection']], function() {
    /**
     * Ruta de Usuario principal
     */
    Route::get('main-users/zones', [
        'uses' => 'MainUsersController@getZones',
        'as' => 'main_users.zones'
    ]);
    Route::resource('main-users', 'MainUsersController');

    /**
     * Ruta de offices
    */
    Route::get('offices/communities', [
        'uses' => 'OfficesController@getCommunities',
        'as' => 'offices.communities'
    ]);
    Route::post('offices/undo/{id}', [
        'uses' => 'OfficesController@postUndelete',
        'as' => 'offices.undelete'
    ]);
    Route::resource('offices', 'OfficesController');

     /**
     * Ruta de employees (Gestión acceso usuarios)
    */
    Route::post('positions/undo/{id}', [
        'uses' => 'PositionsController@postUndelete',
        'as' => 'positions.undelete'
    ]);
    Route::resource('positions', 'PositionsController', ['except' => ['show']]);

    Route::post('employees/status/{id}', [
        'uses' => 'EmployeesController@postSaveStatus',
        'as' => 'employees.save_status'
    ]);
    Route::post('employees/undo/{id}', [
        'uses' => 'EmployeesController@postUndelete',
        'as' => 'employees.undelete'
    ]);
    Route::resource('employees', 'EmployeesController');

    /**
     * Ruta de backups
     */
    Route::get('backups', [
        'uses' => 'BackupsController@getIndex',
        'as'   => 'backups.index'
    ]);
    Route::post('backups', [
        'uses' => 'BackupsController@postExport',
        'as'   => 'backups.export'
    ]);

    /**
     * Ruta de acceso a intranet
    */
    Route::get('intranet', [
        'uses' => 'UsersConnectionsController@getIntranetAccess',
        'as'   => 'connections.intranet'
    ]);

    /**
    * Ruta de usuarios conectados
    */
    Route::get('connections', [
        'uses' => 'UsersConnectionsController@getUsersOnline',
        'as'   => 'connections.online'
    ]);

    /**
     * Ruta de action-history
    */
    Route::get('action-history', [
        'uses' => 'ActionHistoryController@getHistory',
        'as'   => 'history.all'
    ]);

    /**
     *  Ruta de currencies
     */
    Route::post('currencies/undo/{id}', [
        'uses' => 'CurrenciesController@postUndelete',
        'as' => 'currencies.undelete'
    ]);
    Route::resource('currencies', 'CurrenciesController', ['except' => ['show']]);

    /**
     *  Ruta de zones
     */
    Route::post('zones/undo/{id}', [
        'uses' => 'ZonesController@postUndelete',
        'as' => 'zones.undelete'
    ]);
    Route::resource('zones', 'ZonesController', ['except' => ['show']]);
});

/**
 * Rutas para todos los usuarios
 */
Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'user_connection']], function() {

    /**
     * Ruta Perfil de Usuario
     */
    Route::resource('user-profile', 'UsersProfilesController');
});

/**
 * Rutas comúnes
 */
Route::group(['namespace' => 'Common', 'middleware' => ['auth', 'user_connection']], function() {
    Route::resource('language', 'LanguagesController', ['except' => ['show']]);
    Route::resource('country', 'CountriesController', ['except' => ['show']]);
    Route::resource('status', 'StatusController', ['except' => ['show']]);
    Route::resource('payment-method', 'PaymentMethodsController', ['except' => ['show']]);
    Route::resource('contact-type', 'ContactTypesController', ['except' => ['show']]);
    Route::resource('supplier_contact', 'SuppliersContactsController', ['except' => ['show']]);
    Route::resource('supplier_activitie', 'SupplierActivitiesController', ['except' => ['show']]);
    Route::resource('supplier_sector', 'SuppliersSectorsController', ['except' => ['show']]);
    Route::resource('accounting-account', 'AccountingAccountsController', ['except' => ['show']]);
    Route::resource('propertyType', 'PropertyTypesController', ['except' => ['show']]);

app/Models/Zone.php
<?php

namespace Edifalia\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \Venturecraft\Revisionable\RevisionableTrait;

class Zone extends Model
{
    use SoftDeletes;
    use RevisionableTrait;

    protected $revisionCreationsEnabled = true;

    protected $fillable = [ 'name', 'continent_id'];

    protected $dates = ['deleted_at'];

    public function continent()
    {
        return $this->belongsTo(Continent::class);
    }
}

app/Http/Controllers/Backend/ZonesController.php
<?php

namespace Edifalia\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Edifalia\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;
use Edifalia\Repositories\ZoneRepository;
use Illuminate\Validation\Rule;

class ZonesController extends Controller
{
    protected $zoneRepo;

    public function __construct(ZoneRepository $zoneRepo)
    {
        $this->zoneRepo = $zoneRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $zones = $this->zoneRepo->getAll();
        return view('backend.utilities.zones.index', compact('zones'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $header = [
            'route' => 'zones.store',
            'method' => 'POST',
            'role' => 'form',
        ];
        return view('backend.utilities.zones.create_or_edit')->with('header', $header)
            ->with('title', trans('dashboard.titles.add_zone'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \Validator::make($request->all(), [
            'name' => 'required|max:100|unique:zones',
            'continent_id' => 'required|numeric|exists:continents,id',
        ])->validate();

        $zone = $this->zoneRepo->create($request->all());

        Session::flash('message', [
            'alert' => 'success',
            'text' => trans('dashboard.messages.created')
        ]);

        return redirect()->route('zones.edit', $zone->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $zone = $this->zoneRepo->find($id);
        if (is_null($zone))
            return redirect()->route('zones.index');

        $header = [
            'route' => ['zones.update', $zone->id],
            'method' => 'PUT',
            'role' => 'form'
        ];

        return view('backend.utilities.zones.create_or_edit')->with('header', $header)
            ->with('title', trans('dashboard.titles.edit_zone'))
            ->with('zone', $zone);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $zone = $this->zoneRepo->find($id);

        if (is_null($zone))
            return redirect()->route('zones.index');

        \Validator::make($request->all(), [
            'name' => [
                'required',
                'max:100',
                Rule::unique('zones', 'name')->ignore($zone->id)],
            'continent_id' => 'required|numeric|exists:continents,id',
        ])->validate();

        $zone = $this->zoneRepo->update($zone, $request->all());

        Session::flash('message', [
            'alert' => 'success',
            'text' => trans('dashboard.messages.updated')
        ]);
        return redirect()->route('zones.edit', $zone->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if ($request->ajax()) {
            $zone = $this->zoneRepo->find($id);
            if (!is_null($zone)){
                $this->zoneRepo->delete($zone);
                return response()->json([
                    'data' => true,
                    'id' => $id,
                    'message' => trans('dashboard.messages.deleted'),
                    'undo' => trans('dashboard.buttons.undo')
                ]);
            }
            return response()->json([
                'data' => false,
                'message' => trans('dashboard.messages.error')
            ]);
        }
    }

    public function postUndelete(Request $request, $id)
    {
        if($request->ajax()){
            $zone = $this->zoneRepo->recordInTrash($id);
            if (!is_null($zone)){
                $this->zoneRepo->restore($zone);
                return response()->json(['data' => true, 'id' => $id]);
            }
            return response()->json([
                'data' => false,
                'message' => trans('dashboard.messages.error')
            ]);
        }
    }
}

resources/views/backend/utilities/zones/create_or_edit.blade.php
@extends('layouts.dashboard')

@section('breadcrumb_title')
    @lang('dashboard.mnu_zones')
@endsection

@section('breadcrumb_subtitle')
    {{$title}}
@endsection

@section('breadcrumb_map')
    <li>
        <a href="{{ url('dashboard') }}">
            <i class="fa fa-dashboard"></i> @lang('dashboard.home')
        </a>
    </li>
    <li><a href="#">@lang('dashboard.mnu_utilities')</a></li>
    <li class="active">@lang('dashboard.mnu_zones')</li>
@endsection

@section('content')
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">@lang('dashboard.mnu_zones')</h3>
            <div class="btn-group btn-group-sm pull-right">
                <a data-toggle="tooltip" class="btn btn-primary"
                   title="@lang('dashboard.buttons.back')"
                   href="{{route('zones.index')}}">
                    <i class="fa fa-reply"></i></a>
                @if(isset($zone))
                    <a data-toggle="tooltip" class="btn btn-primary"
                       title="@lang('dashboard.buttons.new')"
                       href="{{route('zones.create')}}">
                        <i class="fa fa-plus"></i></a>
                @endif
            </div>
        </div>
        @if(!isset($zone))
            {!! Form::open($header) !!}
        @else
            {!! Form::model($zone, $header) !!}
        @endif
            <div class="box-body">
                @include('backend.partials.messages')
                @include('backend.utilities.zones.fields')
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info">
                    <i class="fa fa-save"></i>
                    @if(!isset($zone))
                        @lang('dashboard.buttons.save')
                    @else
                        @lang('dashboard.buttons.update')
                    @endif
                </button>
            </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/backend/utilities/zones/fields.blade.php
@inject('continents', 'Edifalia\Services\Continents')

<div class="row">
    <div class="form-group col-md-6 {{ $errors->has('name') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.name')) !!}
        {!! Form::text('name', null, [
            'class' => 'form-control',
            'placeholder' => trans('dashboard.fields.name'),
            'required' => true])
        !!}
    </div>
    <div class="form-group col-md-6 {{ $errors->has('continent_id') ? ' has-error' : '' }}">
        {!! Form::label(trans('dashboard.fields.continent')) !!}
        {!! Form::select('continent_id', $continents->get(), null,
            ['class' => 'form-control', 'required' => true])
        !!}
    </div>
</div>

resources/views/backend/utilities/zones/index.blade.php
@extends('layouts.dashboard')

@section('breadcrumb_title')
    @lang('dashboard.mnu_utilities')
@endsection

@section('breadcrumb_subtitle')
    @lang('dashboard.titles.zones_list')
@endsection

@section('breadcrumb_map')
    <li>
        <a href="{{ url('dashboard') }}">
            <i class="fa fa-dashboard"></i> @lang('dashboard.home')
        </a>
    </li>
    <li><a href="#">@lang('dashboard.mnu_utilities')</a></li>
    <li class="active">@lang('dashboard.mnu_zones')</li>
@endsection

@section('modals')
    @include('backend.partials.modals')
@endsection

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">@lang('dashboard.mnu_zones')</h3>
        </div>
        <div class="box-body table-responsive">
            <table class="table table-hover">
                @if($zones->count())
                    <tr>
                        <th>@lang('dashboard.tables.name')</th>
                        <th>@lang('dashboard.tables.continent')</th>
                        <th>@lang('dashboard.tables.actions')</th>
                    </tr>
                @endif
                @forelse($zones as $zone)
                    <tr data-id="{{$zone->id}}"
                        data-rundo="{{route('zones.undelete', $zone->id)}}">
                        <td>{{$zone->name}}</td>
                        <td>{{$zone->continent->name}}</td>
                        <td>
                            <div class="btn-group btn-group-xs">
                                <a data-toggle="tooltip" class="btn btn-info"
                                   title="@lang('dashboard.buttons.edit')"
                                   href="{{route('zones.edit', $zone->id)}}">
                                    <i class="fa fa-pencil-square-o"></i></a>

                                <a data-toggle="tooltip" class="btn btn-info delete_record"
                                   title="@lang('dashboard.buttons.delete')"
                                   href="{{route('zones.destroy', $zone->id)}}">
                                    <i class="fa fa-trash-o"></i></a>
                            </div>
                        </td>
                    </tr>
                @empty
                    <div class="alert alert-warning">
                        <h4><i class="icon fa fa-warning"></i> @lang('dashboard.messages.notice')</h4>
                        @lang('dashboard.messages.no_stored_records')
                    </div>
                @endforelse
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            {{$zones->links()}}
            <a data-toggle="tooltip" class="btn btn-primary pull-right"
               title="@lang('dashboard.buttons.new')"
               href="{{route('zones.create')}}">
                <i class="fa fa-plus"></i> @lang('dashboard.buttons.new')</a>
        </div>
        <!-- /.box-footer-->
    </div>
@endsection

@section('scripts')
    {{-- Backend scripts  --}}
    {!! Html::script('js/code01.js') !!}
@endsection